steps:
  # Step 1: Deploy the model
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: "deploy-model"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir joblib requests google-cloud-storage google-cloud-aiplatform google-auth google-auth-oauthlib google-auth-httplib2 pandas scikit-learn google-cloud-run
        python upload_model.py

serviceAccount: "projects/abhishreya-sharma-ma/serviceAccounts/712745806180-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY