steps:
  # Step 1: Validate the uploaded file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploaded file: $_BUILD_SUBSTITUTION_OBJECT_NAME"
        if [[ "$_BUILD_SUBSTITUTION_OBJECT_NAME" == $_MODEL_DIR* && "$_BUILD_SUBSTITUTION_OBJECT_NAME" == *.pkl ]]; then
          echo "Valid model file detected. Proceeding to deployment step."
        else
          echo "Uploaded file is not a valid model. Skipping deployment."
          exit 0
        fi

  # Step 2: Deploy the model
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir joblib requests google-cloud-storage google-cloud-aiplatform google-auth google-auth-oauthlib google-auth-httplib2 pandas scikit-learn google-cloud-run
        python upload_model.py

serviceAccount: "projects/abhishreya-sharma-ma/serviceAccounts/712745806180-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY