steps:
  # 1. Build Docker Image for Model Deployment
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/abhishreya-sharma-ma/predictor-repo/predictor', '.']

  # 2. Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/abhishreya-sharma-ma/predictor-repo/predictor']

  # 3. Run Model Validation & Conditional Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir joblib requests google-cloud-storage google-cloud-aiplatform google-auth google-auth-oauthlib google-auth-httplib2 pandas scikit-learn google-cloud-run
        python upload_model.py
    serviceAccount: "712745806180-compute@developer.gserviceaccount.com"

images:
  - 'us-central1-docker.pkg.dev/abhishreya-sharma-ma/predictor-repo/predictor'