name: Trigger Model Deployment on Cloud Build

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

env:
  PROJECT_ID: "712745806180"
  REGION: "us-central1"
  CLOUD_BUILD_CONFIG: cloudbuild-model-deploy.yaml
  GCS_BUCKET: "anomaly-detection-knn"
  MODEL_PATH: "models/model.pkl"
  VALIDATION_DATA_PATH: "models/validation_data.csv"

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest
    environment: GCP_SA_KEY 

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate with GCP
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Trigger Cloud Build to Deploy Model
      - name: Trigger Cloud Build for Model Deployment
        run: |
          gcloud builds submit --config $CLOUD_BUILD_CONFIG
